"""add password to users

Revision ID: 1518f15a5013
Revises: 04e752631c15
Create Date: 2026-09-11 17:20:12.711454

"""

import secrets
from collections.abc import Sequence

import bcrypt
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1518f15a5013"
down_revision: str | Sequence[str] | None = "04e752631c15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    users = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("password", sa.String()),
    )

    connection = op.get_bind()

    existing_users = connection.execute(sa.select(users.c.id)).all()

    for user in existing_users:
        generated_password = secrets.token_urlsafe(32)

        hashed_password = bcrypt.hashpw(
            generated_password.encode("utf-8"),
            bcrypt.gensalt(),
        ).decode("utf-8")

        connection.execute(
            users.update().where(users.c.id == user.id).values(password=hashed_password)
        )

    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=255),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
